### ISSUE TITLE
Any way to help code-wise early stage?

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [psycopg/psycopg3#2] opened 2020-05-18 02:30 UTC
I know sponsoring would be great for you, but I don’t have much money. Are there any major OR minor things people can help with? Features, potential bugs, TODOs/FIX
MEs? Or would it break your workflow or mindset of how psycopg3 should be designed?

I think many people would agree that major improvements and milestones should be developed by you based on your blog posts and that aforementioned mindset thing, but others would definitely love to help in some way or another! (e.g. I’m mostly interested in making Django’s ORM async capable, so the async portion would be of interest to me).

**Comment by dvarrazzo** [comment] 2020-05-18 06:36
Hello Andrew,

I have been mostly busy in an optimization sprint: I'm writing a review about it and would like to restart with extending the features set soon.

My guideline would be largely the unit test of psycopg2 and extending the driver until it passes all the tests, - with the due differences. I can maybe try and make public that test suite as it gets butchered?

If you are interested in Django you could make probably a Django db module and report or provide fixes for the features missing. One thing I'm sure is missing is several type adapters: at the moment only strings/number/bools are implemented. Would you like to start from there, for instance with the date adapters?

Let me know, thank you!

**Comment by Andrew-Chen-Wang** [comment] 2020-05-18 15:53
Hi Daniele,

Sure, I can work on the type adapters! However, I made this issue since I felt like the development could use some help from _several_ people. I'm currently in the middle of AP testing (in the US which end this week thankfully), hence me looking for both major and __minor__ things to help with -- sorry. I'm not a reliable contributor for now, and I think most will be like me (this is also my first time contributing for the psycopg project). I guess this issue can more or less be of a roadmap checklist (I believe GitHub provides checkmarks with - [ ], with a space before the dash).

Additionally, it'd also be helpful for documentation on how to contribute. For example, I began testing a date+time and geo adapters on PostgreSQL 12 with a local Python 3.7.6 only to see this combination doesn't seem to be supported via Travis (or did you set up the Travis jobs to be like that so that all Postgres versions were tested with all supported Python versions for faster development? I noticed psycopg2's Travis uses a build matrix). The `test_psycopg3_dbapi20.py` for `test_date_from_ticks` failed on a test on master branch when running pytest for Postgres 12.3 and Python 3.7. Are you using Docker-Compose to do all the testing on each version? Again, it'd be helpful to know your setup so that it's not too big of a barrier to jump in and contribute.

Regarding Django, the community isn't really pushing towards async, except for Andrew Godwin imo since asyncio is a weird library, and many people are afraid of using it, and much of Django is sync, which makes it harder... To continue _that_ development, I'm waiting for some friends to hop on board :)

Besides that... Thanks for this package! Looks great (as far as I can tell)!

**Comment by dvarrazzo** [comment] 2020-05-18 19:56
Hi Andrew,

> I'm currently in the middle of AP testing...

no worries, you don't have to guarantee reliability, I understand perfectly you have other important commitments :)

> I noticed psycopg2's Travis uses a build matrix

Yes, Travis is set up with all the supported python/postgres versions (Python 3.6+, Postgres 9.5+ iirc). But it's not a full NxM grid, rather a diagonal: it only makes sure to test each version once, not each combination once. I think it's an ok start. I am not using docker-compose at the moment.

> The `test_psycopg3_dbapi20.py` for `test_date_from_ticks` failed on a test on master branch when running pytest for Postgres 12.3 and Python 3.7.

Do you mean that it passes for PG 12 on Py 3.8, for PG 11 on Py 3.7, but not on 12+3.7? If there are cases like these probably a full grid would do better, but that starts being a much longer runtime.

> Are you using Docker-Compose to do all the testing on each version?

No, on dev I only run a quick test with whatever I'm developing and let Travis to reproach me if something failed :) I'll review your MR later 

> Regarding Django, the community isn't really pushing towards async.

Well, I can see the reason. Django is entirely based on a sync pattern, both on the database and on the network boundary: I think moving it to async is pretty much a complete rewrite, and every program which wanted move from sync to async would have to be rewritten somehow. I would be happy to have psycopg3 used in Django (I don't think it would be a huge work), but I see it more being used the sync way than the async one.

**Comment by Andrew-Chen-Wang** [comment] 2020-05-21 01:40
> Do you mean that it passes for PG 12 on Py 3.8, for PG 11 on Py 3.7, but not on 12+3.7?

I'm not sure about PG 12 Py3.8 and PG 11 Py 3.7. My machine has PG12.3 and Py 3.7, so that specific test fails when using pytest on my machine. I'm not sure about those other two configurations since I'm not using compose either.

> But it's not a full NxM grid, rather a diagonal

Ah diagonal was the word!

> Django is entirely based on a sync pattern

Yup, haha. The great thing about async Django for me is easier frontend websocket development and greater network performance; that's one of the main reasons why I'd love to push for async. (Django community has websockets with Django channels, but they use some database_sync_to_async method that uses more threads and I don't have a proper throttling algorithm yet).

**Comment by dvarrazzo** [comment] 2020-05-21 01:54
> I'm not sure about PG 12 Py3.8 and PG 11 Py 3.7. My machine has PG12.3 and Py 3.7, so that specific test fails when using pytest on my machine. I'm not sure about those other two configurations since I'm not using compose either.

I mean those configs are tested on travis and they work. What is your error?

> Yup, haha. The great thing about async Django for me is easier frontend websocket development and greater network performance; that's one of the main reasons why I'd love to push for async. (Django community has websockets with Django channels, but they use some database_sync_to_async method that uses more threads and I don't have a proper throttling algorithm yet).

What is the minimal set of features required to write a django engine for psycopg3?

**Comment by Andrew-Chen-Wang** [comment] 2020-05-21 02:50
The traceback:
```
ticks = 0, want = [datetime.date(1970, 1, 1)]

    @pytest.mark.parametrize(
        "ticks, want",
        [
            (0, "1970-01-01"),
            # Returned date is local
            (1273173119.99992, ["2010-05-06", "2010-05-07"]),
        ],
    )
    def test_date_from_ticks(ticks, want):
        s = psycopg3.DateFromTicks(ticks)
        if isinstance(want, str):
            want = [want]
        want = [dt.datetime.strptime(w, "%Y-%m-%d").date() for w in want]
>       assert s in want
E       assert datetime.date(1969, 12, 31) in [datetime.date(1970, 1, 1)]
```

The minimal set of features... for now, take this with a grain of salt, but it's not the features (besides the error messages), as table creation can be kept in a synchronous context, it's this: https://github.com/django/django/blob/master/django/db/backends/postgresql/base.py Every time it says async unsafe or something along those lines.

The rest of the ORM is not dependent on psycopg3 since Django wraps over a cursor. It's mostly the async cursor that is needed as the building of the SQL statements can be done with def functions, right? Unless my asyncio mind is not in the right spot...

**Comment by dvarrazzo** [comment] 2020-05-21 03:09
Building the SQL is done by Django and is outside psycopg3. What django needs is a backend, i.e. a subpackage into `django.db.backends`, with a few settings and a few adaptation function. So, among the things to do there are:

- implement a `django.db.backends.postgresql_psycopg3` package which will likely be mostly the psycopg2 version with a few changes. You can probably do this as an external package
- add missing data types, for instance the dates are not wrapped yet, which is probably the cause of the above, and other missing needed functionality in psycopg3. You can report what they are so we can have a roadmap.

**Closed** 2020-11-23 22:36 UTC
